

CREATE TABLE PRODUCT{
	ID INTEGER
	NAME TEXT
	PRICE INTEGER};

INSERT INTO PRODUCT VALUES(265, "MILK 1L", 100);
INSERT INTO PRODUCT VALUES(875, "ORANGE JUICE 1.25L", 80);
INSERT INTO PRODUCT VALUES(123, "COFFEE 250G", 180);
INSERT INTO PRODUCT VALUES(414, "OIL 5L", 550);
INSERT INTO PRODUCT VALUES(981, "HONEY 100G", 350);

SELECT * FROM PRODUCT ORDER BY PRICE;

CREATE TABLE MARKET{
	ID INTEGER
	QUANTITY INTEGER};

INSERT INTO MARKET VALUES(414, 5);
INSERT INTO MARKET VALUES(875, 10);
INSERT INTO MARKET VALUES(265, 12);
INSERT INTO MARKET VALUES(180, 2);

SELECT * FROM PRODUCT JOIN MARKET ON MARKET.ID = PRODUCT.ID;